-- ========================================================
-- CINEMATCH - SCRIPT DE CRIAÇÃO DO BANCO DE DADOS (SCHEMA)
-- ========================================================

-- Tabela principal para armazenar o diário de filmes dos usuários
CREATE TABLE IF NOT EXISTS filmes_salvos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tmdb_id INT NOT NULL,
    titulo TEXT NOT NULL,
    poster_path TEXT,
    ano TEXT,
    sinopse TEXT,
    status TEXT NOT NULL CHECK (status IN ('quero', 'assistido')),
    nota INT DEFAULT 0
);

-- Comentários para documentação do banco de dados
COMMENT ON TABLE filmes_salvos IS 'Armazena os filmes que os usuários desejam assistir ou que já assistiram.';
COMMENT ON COLUMN filmes_salvos.status IS 'Define a lista do filme: quero (Quero Assistir) ou assistido (Já Assisti).';
COMMENT ON COLUMN filmes_salvos.nota IS 'Avaliação do filme de 1 a 5 estrelas (0 se o status for quero).';